name: Testing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Tests
        run: yarn run test:format